### ISSUE TITLE
Input function produces error when using special characters

### ISSUE THREAD

**Issue by MueJ94** [BashGui/easybashgui#10]
```
export supertitle="Input"
out=$(input 1 "ab*c" 2>&1)
```
produces a write error because the grep statement in the `input` function interprets it as regex pattern. 
`printf -v scelta "%q" "${scelta}"` in line 1426 might fix it.

**Comment by vaisarger** [comment]
Hi @MueJ94 ! 
First of all, _I'm terribly sorry_ for very late reply, I *really* don't know how Github didn't alert me about your comment! I have seen it casually, working to an other issue !
This said, thank you for the issue, user comments help me to find bugs that I never could find...

Well, about the issue you're definitively right: with special chars, grep takes $scelta like regexp!

Your bug fix is very efficient (and safe), so I will definitively put you bugfix in my next release.
Thank you very much!

**Comment by vaisarger** [comment]
Fixed in version 12.0.5
