### ISSUE TITLE
no documentation of embebed projects

### ISSUE THREAD

**Issue by mckaygerhard** [BashGui/easybashgui#12]
the easybashgui said that we could use it in new project but after "install" (install?) it forces me to copy files into system paths. .
"you need to copy in your path" etc etc said the message due the issue #11

the repo provide a makefile procedure but the dialog check, points that we need to copy files into path of the system

**Comment by vaisarger** [comment]
Hi mckaygerhard !

As I said in the other comment, it's true that there isn't any documentation for embedding EBG in projects (without installing it). I'm going to update my site: https://sites.google.com/site/easybashgui/

About makefile, it shows DESTDIR variable to change destination directory:
`DESTDIR ?= ""` 
But installing, as I said, is not mandatory: you can install it but you might simply embed EBG in your project.

About "dialog check" you said, I didn't understand wich check you're talking about.
May you explain a little more ?

**Comment by mckaygerhard** [comment]
ok in resume:

### requirements

* bash
* [src/easybashgui](https://github.com/BashGui/easybashgui/blob/5cb63969e87795e27e69202ef5b7f975db14821b/src/easybashgui)
* [lib/easybashgui.lib](https://github.com/BashGui/easybashgui/blob/5cb63969e87795e27e69202ef5b7f975db14821b/lib/easybashgui.lib)
* [lib/easybashlib](https://github.com/BashGui/easybashgui/blob/5cb63969e87795e27e69202ef5b7f975db14821b/lib/easybashlib)

### how to

1. create directory `mkdir -p /home/general/Devel`
2. create new script for your project: `touch /home/general/Devel/newprogram`
3. echoes the minimal lines to use `echo "#!/usr/bin/env bash\n\nsource ./easybashgui\nmessage hola" > /home/general/Devel/newprogram`
4. run new program `chmod 777 /home/general/Devel/newprogram && /home/general/Devel/newprogram`

**Comment by mckaygerhard** [comment]
i reopen cos i noted README need work i will do a new readme and post a pull requerst to you @vaisarger

**Comment by vaisarger** [comment]
Sure! I would prefere that we work communicating via email (my email address is in README ).
For me it' easier keeping in touch via email... 
( if you don't mind, obviously )
:)

**Comment by mckaygerhard** [comment]
I will prepare a PR with raito, using raito benefits us in the following:

- It does NOT depend on any static site generator or any platform,
- It is a measly single html file that renders the entire content of any MD file.
- allows the website not to depend on updating and take everything directly from the README (and any documentation file in markdown)
- we help and proliferate support for sister projects (Raito) that are free software

that will solve the PR of @zen0bit  at https://github.com/BashGui/easybashgui/pull/9#issuecomment-1944334740 and gives better documentation at the same time, more advanced can be provided later in extended file.. README must be pretty simple and short

**Comment by vaisarger** [comment]
Hi Lenz!

May you explain to me what exactly you mean with "PR" and "raito" ?
Sorry, but I'm not familiar with these terms...

Cheers

Il giorno mer 14 feb 2024 alle ore 19:48 Герхард PICCORO Lenz McKAY <
***@***.***> ha scritto:
