### ISSUE TITLE
please implement or enable discussion on github or use gitlab for better free software support

### ISSUE THREAD

**Issue by mckaygerhard** [BashGui/easybashgui#13]
the main target of this request is to do not populated the issue board.. 

enable the discussion feature of the github or much better use gitlab for better inline with free software principles.. github is not so "free software" per see

**Comment by vaisarger** [comment]
Thank you @mckaygerhard 

Discussion now is enabled.
About Gitlab, I'll take a look at it. 
;)

**Comment by mckaygerhard** [comment]
Closed as done https://github.com/BashGui/easybashgui/discussions
