### ISSUE TITLE
Allow dark theme (switchable) aka: Better website

### ISSUE THREAD

**Issue by zen0bit** [BashGui/easybashgui#20]
My old PR was mainly to use dark theme instead of blindness white (or violet)

I pushed new README to my dark themed pages [meanwhile](https://osowoso.github.io/easybashgui/)

Could raito have dark/light switch?
Or I should ask there @mckaygerhard ?

**Comment by zen0bit** [comment]
Aka nicer website
[Old](https://sites.google.com/site/easybashgui/) website (where i first found you) looks very ugly to me..

**Comment by zen0bit** [comment]
Maybe also Easy Bash Web should be moved/mirrored to github also?
(spoted some bazzar here? never used..)

**Comment by mckaygerhard** [comment]
hi @zen0bit and @vaisarger  now that README and docs has minimal structure please wait for me until i finish the fucntion list.. then i will show you all the auto deploy idea of the website. ..

then you any can code and maybe deploy in any way.. just wait until tomorrow.. please!

**Comment by vaisarger** [comment]
Thanks to @mckaygerhard there are detailed explanations on [(https://github.com/BashGui/easybashgui/discussions/28)] including instructions how to make for google sites or github sites.

Closed.
