### ISSUE TITLE
bug: zenity version dont respect the exit of terminate_wait_for

### ISSUE THREAD

**Issue by mckaygerhard** [BashGui/easybashgui#22]
found a small error, only happened in older versions ooof zenity:

```
source easybashgui

wait_for "I'm sleeping 4 seconds... good night..."
sleep 4
terminate_wait_for
```

raised this:

```
./test.sh 
18638
easybashgui: línea 764: 18637 Tubería rota           yes
     18638 Terminado               | ${dialogo} --title "${supertitle:-EasyBashGUI}: please wait" --progress --pulsate --auto-kill --text "$(echo -e "${testo_zenity}" )" ${dimensione_finestra} &> /dev/null
```

but event using `${wait_for__PID}` it raised.. 

**there is no problem usinig kdialog or yad, dialog just send text and that's normal not tested with xdialog**

**Comment by mckaygerhard** [comment]
after many test i cannnot reproduce it, desktop used for testing was KDE from debian 11..

**Comment by vaisarger** [comment]
I did many tests too, but I had not same problem.

My hypothesis is that message is by bash itself (it communicate to user about background process killed. To see it, you have to type `Enter` and bash communicate you that.
If that is the case, we can't do anything about: it's normal bash behavior.

Unless anyone gives a suggestion... ;)
