### ISSUE TITLE
bug: seems whiptail is not detected if used with wait_for

### ISSUE THREAD

**Issue by mckaygerhard** [BashGui/easybashgui#23]
using code:

```
export supermode="whiptail"

source easybashgui

wait_for "I'm sleeping 4 seconds... good night..."
sleep 4
terminate_wait_for ${wait_for__PID}
```

it raised an error:

```
easybashgui.lib: ERR: "supermode" is not correct.
user@isomaker:~/Devel/easybashgui$ whi
which     while     whiptail  
user@isomaker:~/Devel/easybashgui$ 
```

**Comment by vaisarger** [comment]
There is no "whiptail" mode.
They are:
- yad
- zenity
- Xdialog
- gtkdialog
- kdialog
- dialog
- none
So, if you have whiptail instead of (c)dialog (like Ubuntus ), and you want use it, simply type:
`export supermode=dialog && source easybashgui`

**Comment by mckaygerhard** [comment]
this must be pointed.. the documentation i make wrongly points that supports whiptail so i will made a PR again againt such error.. 

whiptail misunderstand was that i dont noted about the falback way (it enters in text mode when a backend fails, and show text mode), so i assumed whiptail was supported wrongly

**Comment by vaisarger** [comment]
Just to be sure I explained topic in a good way...

Whiptail *is* supported.
In a system with whiptail installed and dialog not installed, you have only
to set "supermode" var to "dialog":
export supermode=dialog && source easybashgui

Il giorno dom 18 feb 2024 alle ore 19:07 Герхард PICCORO Lenz McKAY <
***@***.***> ha scritto:
