### ISSUE TITLE
Create RPMs, DEBs, etc

### ISSUE THREAD

**Issue by wonko21** [BashGui/easybashgui#3]
Use the build service at https://build.opensuse.org/ to create all kinds of "binary" distributions

**Comment by sammcj** [comment]
+1 for RPMs or even an OSX `.app`

If you don't want to use rpmbuild, you could be 'lazy' (says the guy who does this all the time) and use [fpm](https://github.com/jordansissel/fpm)

**Comment by vaisarger** [comment]
Beside .deb package, I need help to make EBG Debian compliant. I need a good person to explain me what is mandatory to make Debian's maintainers happy... :-P

**Comment by mckaygerhard** [comment]
this need more tune up..  before making package.. i already make packages for.. but there ar some issues to solve first.. 

* the paths are hardcoded https://github.com/BashGui/easybashgui/issues/11
* we need to copy files into paths https://github.com/BashGui/easybashgui/issues/12 to work

**Comment by vaisarger** [comment]
Hi mckaygerhard !
I replied in details in #11 and #12 comments.   :)

Thanks for your support, sincerely...

**Comment by mckaygerhard** [comment]
guidelines for packaging are now up to date at https://github.com/BashGui/easybashgui/blob/master/docs/install.md#packaging

**Comment by vaisarger** [comment]
@mckaygerhard 
You did a very good job ! Thank you very much!

**Comment by mckaygerhard** [comment]
i will made pakages on open suse build service.. at the venenux userspace.. and later notify here! will be easy on this weekend

**Comment by vaisarger** [comment]
@mckaygerhard 

Before I close... May I ask you why there are only ".deb" packages and not also ".rpm" ones ?

**Comment by vaisarger** [comment]
@mckaygerhard you are very clever ! Congratulations !

_In your opinion_, what is best way to put this link:
https://software.opensuse.org//download.html?project=home%3Avenenux%3Abashgui&package=easybashgui
in EBG Github page ???

**Comment by mckaygerhard** [comment]
> @mckaygerhard you are very clever ! Congratulations !
> 
> _In your opinion_, what is best way to put this link: https://software.opensuse.org//download.html?project=home%3Avenenux%3Abashgui&package=easybashgui in EBG Github page ???

umm poufff yeah is pretty large.. ok lest do something.. with the page setup .. what about a menu part? the link is pretty large.. i was thinking to put in the menu top of the proposed raito branch page

![image](https://github.com/BashGui/easybashgui/assets/1571724/270b3a18-bf57-4142-9f77-625173dfb2f8)

**Comment by vaisarger** [comment]
I would put that large image (it's ok, actually it's not so large for me ! ) in README.md file, so the link would appear in description of main EBG Github page...

What do you think about ?

**Comment by mckaygerhard** [comment]
umm i am searchig for a badge and about the link we can link the tityle.. wait let me done .. give me 20 mnutes more.. then

testing embebed frame:

<iframe src='https://software.opensuse.org/download/package.iframe?project=projectnamepackage=packagename'></iframe>

**Comment by vaisarger** [comment]
Ok...

Thanks to @mckaygerhard this _OLD_ issue is fixed !

Packages are now available at:
https://software.opensuse.org//download.html?project=home%3Avenenux%3Abashgui&package=easybashgui

Thank you very much @mckaygerhard !
