### ISSUE TITLE
update packages, or automatically use direct sources in OBS

### ISSUE THREAD

**Issue by mckaygerhard** [BashGui/easybashgui#37]
EBG is on 1`3 but OBS debian and rpm packages is still on 12.X.Y

so pending to do ~this week so far~ later.. sorry guys.. mostly around July

**Comment by mckaygerhard** [comment]
Alpine APKBUILD for EBG is upoloaded at https://codeberg.org/alpine/alpine-apkbuilds/src/branch/main/base/easybashgui/APKBUILD with:

```
pkgname=easybashgui
pkgver=13.0.0
pkgrel=0
pkgdesc="aims to give simple GUI functions using yad, gtkdialog, kdialog, zenity, Xdialog, (c)dialog, whiptail or bash builtins"
url="http://bashgui.github.io/easybashgui/"
arch="noarch"
license="MIT"
depends="bash dialog"
makedepends="make"
options="!check"
checkdepends=""
install=""
subpackages="$pkgname-doc"
source="$pkgname-$pkgver.tar.gz::https://github.com/BashGui/easybashgui/archive/$pkgver.tar.gz"

package() {
    make install DESTDIR="$pkgdir"
}

sha512sums="
c5f1fe881c97c9b1ea064e65db7c29a4a64606c57e634cfd1a35cc7c0c56afc3792db87a3ef37098435f8a1f44fda6d0ac657e01a9a877e1dd0e9eeb2b20eaa4  easybashgui-13.0.0.tar.gz
"
```

**Comment by zen0bit** [comment]
Action to release it anyywhere?

**Comment by mckaygerhard** [comment]
no @zen0bit  .. still i not understand so well the github actions.. and i wants something that work in codeberg without consuming codeberg's resources.. theire are good guys and a great organization.. 

i am planning something agnostic like the build setup of nodejs-unnoficial builds.. that the same script works on local and github also..

**Comment by mckaygerhard** [comment]
i update the packages.. but there is no full automatic way.. currelty is semi automatic.. so i'll close.. cos there is no alpine build service apart of alpine oficial! unfortunatelly
