### ISSUE TITLE
website docs migration to github actions

### ISSUE THREAD

**Issue by mckaygerhard** [BashGui/easybashgui#39]
"the time has come and is innevitable"

## Issue:

github was migrated github pages to actions.. this means that any web site deployed now must be converted to github actions..  https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/  all sites now build and deploy with GitHub Actions.

## HOW?

Fortunatelly we do not need a "step of build for pages" our EBG web is totally rendered dinamically on each request.. means thanks ot the power of [Raito](https://github.com/arnaudsm/raito) see it https://raito.arnaud.at/#/

What means? well you only need to directly deploy in the workflow of giuthub actions.. we dont need all of those complicated steps! just direct deploy!

i guess you @zen0bit  has more experience with github actions.. so i wish you to propose a very little file of workflow in the same way you do with deploy of releases! what a wondelfully idea! (also if i try to do it i will take so much time i am pretty slow puff)

## WHY?

that is the reason why the EBG page for docs is stalled when you visit it:

![image](https://github.com/BashGui/easybashgui/assets/1571724/d7f6bebf-e745-42d1-ad5c-387705e75a19)

**Comment by mckaygerhard** [comment]
OH it seems was auto migrated but the http to https redirection does not work:

This is using https
![image](https://github.com/BashGui/easybashgui/assets/1571724/176f07e7-8626-4e97-83df-cd0b11906362)


but with http just a blak page is show

**Comment by mckaygerhard** [comment]
seems done.. i will close 

![image](https://github.com/user-attachments/assets/182435ae-e945-4678-9ca5-a6902e1eee57)

**Comment by DJCrashdummy** [comment]
stupid question: so is the https://sites.google.com/site/easybashgui outdated or not?
or put differently: which site should be used/linked?

**Comment by mckaygerhard** [comment]
Hi maybe for docs.. you should use the https://bashgui.github.io/easybashgui/#/

The  https://sites.google.com/site/easybashgui is the first and original site.. the other one is the site build directly from this repository

**Comment by DJCrashdummy** [comment]
thanks for the reply @mckaygerhard!
i've updated the link in the wiki where i found EBG.
