### ISSUE TITLE
When run on physical tty in whiptail mode, all *message dialogs are white.  This appears to only happen when the console is not framebuffer.

### ISSUE THREAD

**Issue by ciscon** [BashGui/easybashgui#5]
I've tested this by running the following on the console of quite a few boxes, all *message dialogs just give a completely white screen (though functionality still works), other dialogs work fine.  If the console is framebuffer however, everything seems fine.  I'm guessing there is some sort of odd control sequence being output for some reason (I couldn't find anything in the code, though I'm not that familiar with it).  As a workaround installing dialog makes things usable again.

**Comment by vaisarger** [comment]
Since no more notifications on the topic, I'm going to close the issue. Remember _always_ that in text console mode (mode=dialog) you need a terminal with a minimal extent: if you reduce too much the terminal extent (height and width), then widget simply won't work.
