### ISSUE TITLE
suggestion: GUI maker for easybashgui

### ISSUE THREAD

**Issue by zen0bit** [BashGui/easybashgui#8]
Create easy bash gui maker (in easybashgui) for easybashgui so you can easily create guis from GUI

Is it even easy possible?

I am just learning but after, i can try it myself...

:heart: easybashgui

**Comment by mckaygerhard** [comment]
umm i guess we are overeng this.. we have gambas https://gambas.sourceforge.net/ that is a BASIC with gui nativelly into linux so there is no sense, cos basic is more fal easy and also provides more components rather bash itselft

**Comment by zen0bit** [comment]
Never heard about gambas

I'll take a look
Thank you

**Comment by zen0bit** [comment]
But what, should be better readme for TUI/GUI then UI maker implemented in easybash?

I like real word use.

Since this repo looked to me abandoned (❤️ to see activity here)
I moved for TUIs to gum, and created [gumák](https://github.com/oSoWoSo/gumak): TUI maker helper

**Comment by vaisarger** [comment]
Hi @zen0bit :)

AS I said, Github has made a not good job in keeping me updated about comments! Anyway...

About this present request, EBG is an "atomic" message system to user: 1 thing to say or ask, to 1 user.
This is the spirit.
Reason of this is also thet: it would be impossible make so different widgets to do same thing, in a tranparent way for the user (and the scripter).

For a more complicated GUI maker, you have *many* options out there.
Years ago there was Gtkdialog, but many many years ago there was TCL/Tk, now there are so many...

**Comment by zen0bit** [comment]
> Hi @zen0bit :)
> 
> AS I said, Github has made a not good job in keeping me updated about comments! Anyway...
> 
> About this present request, EBG is an "atomic" message system to user: 1 thing to say or ask, to 1 user. This is the spirit. Reason of this is also thet: it would be impossible make so different widgets to do same thing, in a tranparent way for the user (and the scripter).
> 
> For a more complicated GUI maker, you have _many_ options out there. Years ago there was Gtkdialog, but many many years ago there was TCL/Tk, now there are so many...

They are to complicated. I am looking at something as easy as possible for use in bash. (like ebg, yad [wayland issues], clossest which I am aware of is gum)

😇 Apology that I never really completed any of my UIs in ebg. But know a lot less back then. A then put in storage, maybe a will take them out🧐

If this project is still alive

**Comment by vaisarger** [comment]
Hi @zen0bit !

I

> If this project is still alive

If you mean EasyBashGUI, is absolutely alive! Github didn't notify me some comment in these two years, but it was a pity because I would appreciate support to make this project better and better...

Obviously I dedicate time to the project of my *free* time, but, you know... much of O.S. world is like so!

Please, let me know any opinions or suggestions...

**Comment by vaisarger** [comment]
About this present request, EBG is an "atomic" message system to user: 1 thing to say or ask, to 1 user. Take his answer, and go forth...
This is the spirit.

Reason of this is also that: it would be impossible make so many different widgets do same thing, in a transparent way for the user (and the scripter).
